;; This file was generated by the `with-cache` library on 2021-04-28
(((forth fsm fsmoo mbta morsecode zombie dungeon jpeg zordoz lnm suffixtree kcfa snake take5)) (3) 0 () 0 () () (q (forth . #f) (fsm . 11/10) (fsmoo . #f) (mbta . 17/10) (morsecode . 11/10) (zombie . #f) (dungeon . 16/5) (jpeg . 8/5) (zordoz . 17/10) (lnm . 6/5) (suffixtree . #f) (kcfa . 6/5) (snake . #f) (take5 . 16/5)))
